# Generated by Django 5.1.4 on 2024-12-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_announces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announces',
            new_name='Liste',
        ),
    ]
