# Generated by Django 5.1.4 on 2024-12-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_liste_description_liste_sold_liste_type_liste_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
