# Generated by Django 5.1.4 on 2024-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_livre_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(default='YAOUNDE', max_length=100),
            preserve_default=False,
        ),
    ]
